default_language_version:
  python: python3.9

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      # - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        types: [html]
        additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/browniebroke/django-codemod
    rev: v1.10.6
    hooks:
      - id: djcodemod
        stages: [manual]
        args: [
          "run",
          "--deprecated-in", "1.9",
          "--deprecated-in", "1.10",
          "--deprecated-in", "1.11",
          "--deprecated-in", "2.0",
          "--deprecated-in", "2.1",
          "--deprecated-in", "2.2",
          "--removed-in", "3.0",
          "--deprecated-in", "3.0",
          "--deprecated-in", "3.1",
          "--removed-in", "4.0",
        ]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.7.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.0"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
        args: [--py3-plus, --py39-plus]
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.3.3
    hooks:
      - id: pycln
        exclude: ^manage.py
        args: [--all]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --remove-redundant-aliases
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
      - id: blacken-docs
        additional_dependencies: ['black==22.1.0', 'click==8.0.4']
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: ["--ignore=E203,E501,W503","--exclude=manage.py"]
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-print
          - flake8-no-pep420
          - flake8-tidy-imports
